name: chopper_api_anit
description: A new Flutter module project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  chopper: ^4.0.6
  dio: ^4.0.4 

 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.1.7
  chopper_generator: ^4.0.6
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  swagger_dart_code_generator: ^2.4.6



flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  
  module:
    androidX: true
    androidPackage: com.example.chopper_api_anit
    iosBundleIdentifier: com.example.chopperApiAnit
