// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8riIT84Vi_CisKSRxCS10Jg0RA7Vtlrw',
    appId: '1:332960776156:web:6fdc01bd0fdfc970989919',
    messagingSenderId: '332960776156',
    projectId: 'test-notification-657de',
    authDomain: 'test-notification-657de.firebaseapp.com',
    storageBucket: 'test-notification-657de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP45bUbNagB3qntcQobCXDSKEKm9O2P3M',
    appId: '1:332960776156:android:2d843db9247f84a5989919',
    messagingSenderId: '332960776156',
    projectId: 'test-notification-657de',
    storageBucket: 'test-notification-657de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0wqa23CcqtzqhWuHilerEhy_raG9Q1A',
    appId: '1:332960776156:ios:aea27665c64f80e3989919',
    messagingSenderId: '332960776156',
    projectId: 'test-notification-657de',
    storageBucket: 'test-notification-657de.appspot.com',
    iosClientId: '332960776156-tq4vpmn5ld0cvgahdij8m9ds9ockf2nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA0wqa23CcqtzqhWuHilerEhy_raG9Q1A',
    appId: '1:332960776156:ios:aea27665c64f80e3989919',
    messagingSenderId: '332960776156',
    projectId: 'test-notification-657de',
    storageBucket: 'test-notification-657de.appspot.com',
    iosClientId: '332960776156-tq4vpmn5ld0cvgahdij8m9ds9ockf2nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestNotification',
  );
}
